import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { BarChart, Button, Card, Divider, Row, SectionTitle } from '../components/UI';
import { ScreenHeader } from '../components/ScreenHeader';
import { weeklyProduction } from '../data/mockData';
import { colors, spacing, typography } from '../theme';

export const ReportDetailScreen: React.FC<{ params?: any }> = ({ params }) => {
  const r = params || { title: 'Daily Production Report', subtitle: 'Output, rejects, downtime', icon: '🏭' };
  return (
    <View style={{ flex: 1, backgroundColor: colors.bg }}>
      <ScreenHeader title={r.title} subtitle={r.subtitle} rightIcon="↗" />
      <ScrollView contentContainerStyle={{ padding: spacing.lg, paddingBottom: spacing.xxl }}>
        <Card>
          <View style={{ flexDirection: 'row', alignItems: 'center' }}>
            <Text style={{ fontSize: 36 }}>{r.icon}</Text>
            <View style={{ flex: 1, marginLeft: 12 }}>
              <Text style={typography.h2}>{r.title}</Text>
              <Text style={typography.small}>22 Apr 2026 · Plant 1 — Pune</Text>
            </View>
          </View>
          <Divider />
          <Row label="Period" value="Last 7 days" />
          <Row label="Generated by" value="Ravi Verma · Plant Manager" />
          <Row label="Format" value="PDF / Excel / CSV" />
        </Card>

        <SectionTitle title="Headline KPIs" />
        <View style={{ flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }}>
          {[
            { n: '6,012', l: 'Output (pcs)' },
            { n: '94%', l: 'Quality' },
            { n: '78%', l: 'Utilization' },
            { n: '1.7%', l: 'Rejection' },
          ].map((k) => (
            <View key={k.l} style={styles.kpi}>
              <Text style={{ fontSize: 18, fontWeight: '900', color: colors.text }}>{k.n}</Text>
              <Text style={{ fontSize: 11, color: colors.textMuted, fontWeight: '700' }}>{k.l}</Text>
            </View>
          ))}
        </View>

        <SectionTitle title="Trend" />
        <Card>
          <BarChart data={weeklyProduction} color={colors.primary} labels={['M','T','W','T','F','S','S']} />
        </Card>

        <SectionTitle title="Breakdown" />
        <Card>
          <Row label="Line A · CNC" value="2,140 pcs · 92% eff" />
          <Row label="Line B · VMC" value="1,890 pcs · 88% eff" />
          <Row label="Line C · Furnace" value="540 pcs · 62% eff" />
          <Row label="Line D · Lathe"  value="1,442 pcs · 80% eff" />
        </Card>

        <View style={{ flexDirection: 'row', marginTop: spacing.lg }}>
          <Button label="Download PDF" full style={{ flex: 1, marginRight: 8 }} />
          <Button label="Email Report" variant="secondary" full style={{ flex: 1, marginRight: 8 }} />
          <Button label="Schedule"     variant="ghost" full style={{ flex: 1 }} />
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  kpi: { width: '48.5%', backgroundColor: colors.surface, borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: spacing.md, marginBottom: 10 },
});
